### ISSUE TITLE
Somfy Blinds

### ISSUE THREAD

**Issue by hi-flyer** [bondhome/bond-cli#43]
Am considering a Bond hub but I need it to activate Somfy blinds. The Bond App says it does Somfy Blinds. Does the info for Somfy Blinds automatically come into bond-cli somehow. I know they have a rolling code so it seems the database needs to come into bond-cli somehow.
TIA for info.

**Comment by jdlambert** [comment]
Somfy devices on the Bond Bridge are backed by a script stored in its database.

The rolling code behavior is achieved by tracking a couple counters, which are passed to the script (along with an address and action to perform), which then generates the proper signal.

Gonna close this issue but if you have more questions, I'd be happy to answer them.

**Comment by hi-flyer** [comment]
Appreciate the response.
but from the user of your software, do the have to deal with the BondBridge script or is it automatically deal?

Sorry, but I am not clear.

**Comment by jdlambert** [comment]
This script is included in the Bond Bridge firmware, the mobile app (or this CLI, or any other HTTP client) can set up a Somfy device, so there's no need for the user to think about the behavior of the script.

It is on our roadmap to eventually have custom user scripts, though.
