### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by hi-flyer** [bondhome/bond-cli#48]
I am trying to do the following but do not understand what the data format is for the somfy sunsetter blinds.
bond signal --data ? --freq 433000.
returns HTTP 400 data does not match specified encoding (this changes depending on what I put in the ? obviously) example
{"put http://192.168.1.235/v2/devices/3c7e2a69/actions/close"}
where do I find the correct encoding format. tried the doc on http formats but I failed with those. 

ultimately hoping to integrate bond hub into nymea as a plugin using bond-cli
.

**Comment by chrismerck** [comment]
Sunsetter/Somfy uses a rolling code that changes every time, so you probably wouldn't want to manually construct the signal on the client-side. Let the Bridge do it.

Try this:

`curl -iH "Bond-Token: xxxx" http://192.168.1.235/v2/devices/3c7e2a69/actions/Close -X PUT -d {}`

Note the need to replace your token in the `xxx` and the case-sensitivity of the URL.

**Comment by hi-flyer** [comment]
Thanks for the hint, appreciate it.
